### ISSUE TITLE
The crowdmap should save and reapply room marks when updates occur.

### ISSUE THREAD

**Issue by Asteria-UI** [Asteria-UI/AsteriaCrowdmap#8]
Additions to the updating script should be made so that it tables any existing room marks, and reapplies them upon successful update, so that users can make full use of the room mark feature.

Check for update - > sees update! -> saves marks -> does update -> update success! -> apply marks.

**Comment by MentalThinking** [comment]
According to this [rather obvious part of the mapper wiki](https://wiki.mudlet.org/w/IRE_mapping_script#What_is_the_difference_between_a_room_mark_and_a_map_feature.3F), the script already saves marks on a per-user basis, and thus, this issue can be closed.
